### PR TITLE
Fix #23: return error rather than panic if index is out of bounds

### LINKED ISSUE #23: Index out of bounds at huffman_tree.rs line 252 when reading invalid data
When trying to decompress an invalid file, I get the following panic. I'll post the reproducing steps ASAP.
```
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deflate64-0.1.7/src/huffman_tree.rs:252:21:
index out of bounds: the len is 64 but the index is 64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==4066== ERROR: libFuzzer: deadly signal
    #0 0x561a8eb7d991  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x20a991) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #1 0x561a8eeb250e  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x53f50e) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #2 0x561a8eeba959  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x547959) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #3 0x7f2ecfa4251f  (/lib/x86_64-linux-gnu/libc.so.6+0x4251f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #4 0x7f2ecfa969fb  (/lib/x86_64-linux-gnu/libc.so.6+0x969fb) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #5 0x7f2ecfa42475  (/lib/x86_64-linux-gnu/libc.so.6+0x42475) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #6 0x7f2ecfa287f2  (/lib/x86_64-linux-gnu/libc.so.6+0x287f2) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #7 0x561a8ef58a06  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5e5a06) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #8 0x561a8ead97f6  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x1667f6) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #9 0x561a8ee9d014  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x52a014) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #10 0x561a8ef4daaf  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5daaaf) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #11 0x561a8ef4d7f1  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5da7f1) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #12 0x561a8ef4ada5  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5d7da5) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #13 0x561a8ef4d523  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5da523) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #14 0x561a8eadc184  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x169184) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #15 0x561a8eadc371  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x169371) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #16 0x561a8eddc3a4  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x4693a4) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #17 0x561a8eddab1b  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x467b1b) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #18 0x561a8ede4189  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x471189) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #19 0x561a8edde7da  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x46b7da) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #20 0x561a8edddb50  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x46ab50) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #21 0x561a8ec35c3a  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x2c2c3a) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #22 0x561a8ec53552  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x2e0552) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #23 0x561a8ec56f34  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x2e3f34) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #24 0x561a8ec5ebc9  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x2ebbc9) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #25 0x561a8ebb1bb4  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x23ebb4) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #26 0x561a8ebc5868  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x252868) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #27 0x561a8ebb3326  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x240326) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #28 0x561a8ebe3432  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x270432) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #29 0x561a8ebe4272  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x271272) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #30 0x561a8ebe3c50  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x270c50) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #31 0x561a8ee97fff  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x524fff) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #32 0x561a8ee9d227  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x52a227) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #33 0x561a8ee9c74b  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x52974b) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #34 0x561a8eebaea5  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x547ea5) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #35 0x561a8eec02c3  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x54d2c3) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #36 0x561a8eec12b8  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x54e2b8) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #37 0x561a8eec36a7  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x5506a7) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #38 0x561a8eeabf3f  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x538f3f) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #39 0x561a8eadc9b6  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x1699b6) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
    #40 0x7f2ecfa29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #41 0x7f2ecfa29e3f  (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
    #42 0x561a8eadcb54  (/home/runner/work/zip-next/zip-next/fuzz/target/x86_64-unknown-linux-gnu/release/fuzz_read+0x169b54) (BuildId: 9461613681e50016bf6b7ede80d99caa605d2588)
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

### PR DESCRIPTION
**Pull request by Pr0methean**
Prevents a panic when the Huffman tree is invalid.

### CODE REVIEW

File: src/huffman_tree.rs [hunk 1]
```diff
@@ -243,6 +244,13 @@ impl HuffmanTree {
                         }
                         index = -value as usize; // go to next node
 
+                        if index
+                            >= 2 * min(self.code_lengths_length as usize, Self::MAX_CODE_LENGTHS)
+                        {
```
Comment (anatawa12) [inline src/huffman_tree.rs:249]:
```suggestion
                        if index >= array.len() {
```

I think this is easier to read.

**Comment by anatawa12** [comment]
Thank you for pull request

**Review by NobodyXu — APPROVED** [review]
