### PR TITLE
Fix err with some archive

### LINKED ISSUE #13: Impossilbe to decompress `Editor/Logo/UnlitWFロゴ_1024.png` of unlitWF
`Editor/Logo/UnlitWFロゴ_1024.png` of [UnitWF](https://github.com/whiteflare/Unlit_WF_ShaderSuite/releases/download/UnlitWF_Shader_20231011/jp.whiteflare.unlitwf-1.5.0.zip) is not possible to decompress.

I have found location of the problem so I'm going to create pull request.

### PR DESCRIPTION
**Pull request by anatawa12**
Fix #13

### CODE REVIEW

File: src/output_window.rs [hunk 1]
```diff
@@ -109,7 +109,7 @@ impl OutputWindow {
             }
         } else {
             // only one copy is needed if there is no wrap around.
-            copied = input.copy_to(&mut self.window[self.end..][..tail_len]);
+            copied = input.copy_to(&mut self.window[self.end..][..length]);
```
Comment (anatawa12) [inline src/output_window.rs:112]: https://github.com/dotnet/runtime/blob/bd83e17052d3c09022bad1d91dca860ca6b27ab9/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateManaged/OutputWindow.cs#L106

Comment (NobodyXu) [inline src/output_window.rs:112]: Could use one slice instead of two:

```suggestion
            copied = input.copy_to(&mut self.window[self.end..length]);
```

**Review by NobodyXu — CHANGES_REQUESTED** [review]

File: src/output_window.rs (hunk 1 above)
Comment (anatawa12) [reply src/output_window.rs:112]: We should not. `[x..y]` means since x-th (inclusive) until y-th (exclusive), `[x..][..y]` means since x-th (inclusive) length y

```
fn main() {
    println!("{:?}", &[0,1,2,3,4,5][1..3]); // [1, 2]
    println!("{:?}", &[0,1,2,3,4,5][1..][..3]); // [1, 2, 3]
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a111cbb5af9e6bf3f826b280a2f3e4b8

Comment (NobodyXu) [reply src/output_window.rs:112]: Thanks for explanation!

I forgot that you would need `[end..(end + length)]`

**Review by NobodyXu — APPROVED** [review]
